#!/bin/bash

func_usage ()
{
  echo " Create php-fpm configuration for specific provision"
  echo " Usage : $0 -d domain -u user "
  exit 1
}

while getopts d:u: OPT
  do
    case $OPT in
	 "d" ) PROV="$OPTARG" ;;
	 "u" ) USERNAME="$OPTARG" ;;
	 * ) func_usage ;;
	esac
  done

if [ -z ${PROV} ] || [ -z ${USERNAME} ]; then
  func_usage
fi

# create separate php53-fpm configuration for each vhost
sed -e 's/%%DOMAIN%%/'$PROV'/' /etc/php-fpm.d/conf.d/php-fpm.conf.template > /etc/php-fpm.d/conf.d/$PROV.conf

# create separate pool configuration for each vhost
sed -e 's/%%DOMAIN%%/'$PROV'/' -e 's/%%USER%%/'$USERNAME'/' /etc/php-fpm.d/www.conf.template > /etc/php-fpm.d/www.$PROV.conf

# create new service
sed -e 's/%%DOMAIN%%/'$PROV'/' /usr/lib/systemd/system/php-fpm.service.template > /usr/lib/systemd/system/php-fpm.$PROV.service

## Start service
systemctl daemon-reload
systemctl start php-fpm.$PROV.service
systemctl enable php-fpm.$PROV.service



