#!/bin/bash

func_usage ()
{
  echo " Create php7-fpm configuration for specific provision"
  echo " Usage : $0 -d domain -u user "
  exit 1
}

while getopts d:u: OPT
  do
    case $OPT in
	 "d" ) PROV="$OPTARG" ;;
	 "u" ) USERNAME="$OPTARG" ;;
	 * ) func_usage ;;
	esac
  done

if [ -z ${PROV} ] || [ -z ${USERNAME} ]; then
  func_usage
fi

# create separate php7-fpm configuration for each vhost
sed -e 's/%%DOMAIN%%/'$PROV'/g' /etc/php7-fpm.d/conf.d/php7-fpm.conf.template > /etc/php7-fpm.d/conf.d/$PROV.conf

# create separate pool configuration for each vhost
sed -e 's/%%DOMAIN%%/'$PROV'/g' -e 's/%%USER%%/'$USERNAME'/g' /etc/php7-fpm.d/www.conf.template > /etc/php7-fpm.d/www.$PROV.conf

# create new service
sed -e 's/%%DOMAIN%%/'$PROV'/g' /usr/lib/systemd/system/php7-fpm.service.template > /usr/lib/systemd/system/php7-fpm.$PROV.service

## Start service
systemctl daemon-reload
systemctl start php7-fpm.$PROV.service
systemctl enable php7-fpm.$PROV.service

