#!/bin/bash
##################################
# Config
##################################
CONFIGFILE=`dirname $0`/*.cfg
source ${CONFIGFILE} || exit
##################################
func_usage ()
{
  echo '##USAGE##'
  echo "  $0 -c ContainerName"
  exit 1
}

while getopts c: OPT
do
  case $OPT in
    "c" ) CNAME="$OPTARG" ;;
     * ) func_usage ;;
  esac
done

#Check Arguments
if [ -z ${CNAME} ]; then
  func_usage
fi

# Post Data
curl -X POST \
-H "Accept: application/json" \
-H "Content-Type: application/json" \
-H "X-Auth-Token: ${TOKEN}" \
-H "X-Container-Read: .r:*" \
${OBJ_URL}/${OBJ_PREFIX}${TENANT_ID}/${CNAME}

exit 0
