#!/bin/bash
function usage()
{
	echo " Remove user and all provision belong to it"
	echo " Usage $0 -u user "
	exit 1
}
while getopts u: OPT
	do
		case $OPT in
		  "u" ) USERNAME="$OPTARG" ;;
		  "*" ) usage ;;
		esac
	done
if [ -z ${USERNAME} ]; then
	usage
fi

GetP=`cat /usr/src/.lifesafty_cPanel | head -c 24`
delete_php_conf()
{
RET=`systemctl is-active $1-fpm.$USERNAME | grep -w "active" 2>&1 > /dev/null;echo $?`
if [ $RET -eq 0 ]; then
	systemctl stop $1-fpm.$USERNAME
	systemctl disable $1-fpm.$USERNAME
	rm -f /etc/$1-fpm.d/conf.d/$USERNAME.conf
	rm -f /etc/$1-fpm.d/www.$USERNAME.conf
	rm -f /usr/lib/systemd/system/$1-fpm.$USERNAME.service
elif [ -f "/usr/lib/systemd/system/$1-fpm.$USERNAME.service" ]; then
    systemctl disable $1-fpm.$USERNAME
	rm -f /etc/$1-fpm.d/conf.d/$USERNAME.conf
    rm -f /etc/$1-fpm.d/www.$USERNAME.conf
    rm -f /usr/lib/systemd/system/$1-fpm.$USERNAME.service
fi
}
delete_hhvm_conf()
{
RET=`systemctl is-active hhvm.$USERNAME | grep -w "active" 2>&1 > /dev/null;echo $?`
if [ $RET -eq 0 ]; then
	systemctl stop hhvm.$USERNAME
	systemctl disable hhvm.$USERNAME
	rm -f /etc/hhvm/conf.d/$USERNAME.ini
	rm -f /var/cache/hhvmd/$USERNAME.*
	rm -f /etc/systemd/system/hhvm.$USERNAME.service
elif [ -f "/etc/systemd/system/hhvm.$USERNAME.service" ] ; then
	systemctl disable hhvm.$USERNAME
    rm -f /etc/hhvm/conf.d/$USERNAME.ini
    rm -f /var/cache/hhvmd/$USERNAME.*
    rm -f /etc/systemd/system/hhvm.$USERNAME.service
fi
}
delete_php_conf php7
delete_php_conf php
systemctl daemon-reload
#Delete user from account table
mysql -p$GetP kusanagi -e "DELETE FROM account WHERE login_id = '"$USERNAME"'"
echo "Drop Userdb" $?
#Delete_provision
/usr/src/remove_all_provision -u $USERNAME;echo $?
echo "Drop ALL Provision" $?
#Delete Filerun
sed -i "/$USERNAME/d" /usr/src/clean-Filerun
mysql -p$GetP -e "DROP DATABASE IF EXISTS Filerun_"$USERNAME"_db"
echo "Drop Filerun_"$USERNAME"_db $?"
mysql -p$GetP -e "DROP USER 'Filerun_"$USERNAME"_user'@'%'"
echo "Filerun_"$USERNAME"_user" $?
uid=`id -u $USERNAME`
# remove from dbuser-map
dbctl delete $USERNAME
sed -i '/'$uid'/d' /etc/container/dbuser-map

# remove from lvectl
lvectl destroy $uid
userdel --remove $USERNAME 
sed -i '/'$USERNAME':/d' /root/.hungpham/userpass_list.log
sed -i '/'$uid'/d' /var/superpanel/user_package
sed -i '/'$uid',/d' /var/superpanel/users
#rm -rf /var/log/$USERNAME
