#!/bin/bash

usage () {
	echo "$0 -u user -d domain"
	exit 1
}
while getopts u:d: OPT
do
	case $OPT in
	"u" ) _user="$OPTARG" ;;
	"d" ) _doma="$OPTARG" ;;
	*   ) usage ;;
	esac
done
if [ -z ${_user} ] || [ -z ${_doma} ]; then
	usage
fi

source /usr/src/check_alive_token
get_token="/usr/src/get_token"
get_detail="/usr/src/obj-get-cont-detail"
del_obj="/usr/src/obj-del-obj"

cleanup() {
	## remove backup file older than 05 days
	srv_hostname=`hostname`
	dest_url="file:///backup/$srv_hostname/${_user}/${_doma}"
	dest_path="/backup/$srv_hostname/${_user}/${_doma}"
	log_archive="/var/log/${_doma}/archive_bk.log"
	echo "Cleanup ${_user}: ${_doma}"
	if [ -d "$dest_path" ]; then
		if [ -f "$log_archive" ]; then
			duplicity remove-older-than 5D $dest_url --force >> $log_archive
		else
			duplicity remove-older-than 5D $dest_url --force > /dev/null
		fi
		if [ $? -gt 0 ]; then
			source /usr/src/common_function
			fix_backup ${_user} ${_doma}
		fi
		if [ ! -d "/home/${_user}/${_doma}" ] && [ 0 -eq $(ls $dest_path | wc -l) ]; then
			sed -i '/d '${_doma}'/d' /etc/cron.weekly/cleanbk-prov
			rm -rf $dest_path
		fi
	else
		[ -f "$dest_path" ] && rm -f $dest_path
		mkdir $dest_path
	fi

	## remove sql tar file older than 7D on swift
	threshold=604800
	alive=$(check_alive_token)
	[ $alive -eq 0 ] && $get_token
	$get_detail -c sqlbackup?prefix=${srv_hostname}/${_user}/${_doma} | jq '.name' | tr -d '\"' |\
	while read obj; do
		dob=`echo $obj | cut -d '/' -f 4`
		m=$((`date +%s` - `date -d "$dob" +%s`))
		if [ $m -gt $threshold ]; then
			echo "--- "$obj
			$del_obj -c sqlbackup -o $obj
		fi
	done
}

cleanup
exit 0
