#!/bin/bash

# add a new user
GetP=`cat /usr/src/.lifesafty_cPanel | head -c 24`
FileP=`openssl rand -base64 32`
function usage() {
   echo " Usage $0 -u user -p plan_number"
   exit 1
}

create_log_dir() {
	mkdir /home/$AMAN/log/$1
	mkdir /home/$AMAN/log/$1/session
    mkdir /home/$AMAN/log/$1/wsdlcache

	chown $AMAN:$AMAN /home/$AMAN/log/$1
	chown root:$AMAN /home/$AMAN/log/$1/session
	chown $AMAN:$AMAN /home/$AMAN/log/$1/wsdlcache
	chmod 775 /home/$AMAN/log/$1/session
	touch /home/$AMAN/log/$1/session/.protected
	chattr +i /home/$AMAN/log/$1/session/.protected
}

while getopts u:p: OPT
	do
		case $OPT in
		 "u" ) AMAN="$OPTARG" ;;
		 "p" ) PLAN="$OPTARG" ;;
		 "*" ) usage ;;
		esac
	done
if [ -z ${AMAN} ] || [ -z ${PLAN} ]; then
	usage
fi
dquota[1]=7168
dquota[2]=20480
dquota[3]=35480
iquota[1]=200000
iquota[2]=300000
iquota[3]=500000
pkg[1]='Start'
pkg[2]='Business'
pkg[3]='Professional'
bhard=${dquota[$PLAN]}
let bsoft=bhard-100
ihard=${iquota[$PLAN]}
let isoft=ihard-2000

if [ `grep $AMAN /etc/passwd >/dev/null 2>&1;echo $?` -eq 0 ]; then
   	echo " User existed, please enter another one"
	exit 1
else
	useradd $AMAN
	cd /home
	chcon unconfined_u:object_r:user_home_dir_t:s0 $AMAN
	chmod 701 $AMAN

	# create a password
	PASSWORD=`head /dev/urandom | tr -dc A-Za-z0-9 | head -c 12`
	echo "$AMAN:$PASSWORD" >> /root/.hungpham/userpass_list.log
	echo -e "$PASSWORD\n$PASSWORD\n" | passwd $AMAN

	mkdir /home/${AMAN}/log
	chown root:root /home/${AMAN}/log
	create_log_dir php7
	create_log_dir php-fpm
	for i in php php71 php72 php73 php74
	do
		/usr/src/create-${i}-conf -d $AMAN -u $AMAN
	done
	
	source /usr/src/common_function
	create_fr $AMAN
	
	sed -i "/kusanagilifesafe_user/a\    'deny Filerun_${AMAN}_user from all'," /usr/share/mysqlmanager/config.inc.php
	echo -e "/usr/src/clean_Filerundb -u $AMAN" >> /usr/src/clean-Filerun
	# set disk quota
	xfs_quota -x -c 'limit bsoft='$bsoft'm bhard='$bhard'm '$AMAN'' /home
	xfs_quota -x -c 'limit -g bsoft='$bsoft'm bhard='$bhard'm '$AMAN'' /home
	# set inode quota
	xfs_quota -x -c 'limit isoft='$isoft' ihard='$ihard' '$AMAN'' /home
	xfs_quota -x -c 'limit -g isoft='$isoft' ihard='$ihard' '$AMAN'' /home
	# apply to lve limit
	uid=`id -u $AMAN`
	echo $uid ${pkg[$PLAN]} >> /var/superpanel/user_package
	echo $uid","${pkg[$PLAN]}"," >> /var/superpanel/users
	lvectl apply $uid
	# update dbuser belong to this user to dbuser-map file
	/usr/src/dbuser-map-update $AMAN
	# cagefs custom
	mkdir -p /etc/cagefs/custom.etc/$AMAN
	cp -f /usr/src/cPanel/hosts /etc/cagefs/custom.etc/$AMAN/hosts
	chown -R $AMAN:$AMAN /etc/cagefs/custom.etc/$AMAN/
	cagefsctl --update-etc $AMAN
	echo " /usr/local/maldetect/maldet --scan-all /home/$AMAN" >> /usr/src/maldet_user
	exit 0
fi
