#!/bin/bash

GetP=`cat /usr/src/.lifesafty_cPanel | head -c 24`
FileP=`openssl rand -base64 32`

function usage() {
   echo " Usage $0 -u user"
   exit 1
}

while getopts u: OPT
	do
		case $OPT in
		 "u" ) AMAN="$OPTARG" ;;
		 "*" ) usage ;;
		esac
	done
if [ -z ${AMAN} ]; then
	usage
fi

source /usr/src/common_function
create_fr $AMAN

exit 0
