#!/bin/bash

# add a new user
GetP=`cat /usr/src/.lifesafty_cPanel | head -c 24`
FileP=`openssl rand -base64 32`
function usage() {
   echo " Usage $0 -u user -p plan_number"
   exit 1
}

create_log_dir() {
	mkdir /home/$AMAN/log/$1
	mkdir /home/$AMAN/log/$1/session
    mkdir /home/$AMAN/log/$1/wsdlcache
}

while getopts u:p: OPT
	do
		case $OPT in
		 "u" ) AMAN="$OPTARG" ;;
		 "p" ) PLAN="$OPTARG" ;;
		 "*" ) usage ;;
		esac
	done
if [ -z ${AMAN} ] || [ -z ${PLAN} ]; then
	usage
fi
dquota[1]=7168
dquota[2]=20480
dquota[3]=35480
iquota[1]=200000
iquota[2]=300000
iquota[3]=500000
pkg[1]='Start'
pkg[2]='Business'
pkg[3]='Professional'
bhard=${dquota[$PLAN]}
let bsoft=bhard-100
ihard=${iquota[$PLAN]}
let isoft=ihard-10000

if [ `grep $AMAN /etc/passwd >/dev/null 2>&1;echo $?` -eq 0 ]; then
   	echo " User existed, please enter another one"
	exit 1
else
	useradd $AMAN
	cd /home
	chcon unconfined_u:object_r:user_home_dir_t:s0 $AMAN
	chmod 701 $AMAN

	# create a password
	PASSWORD=`head /dev/urandom | tr -dc A-Za-z0-9 | head -c 12`
	echo "$AMAN:$PASSWORD" >> /root/.hungpham/userpass_list.log
	echo -e "$PASSWORD\n$PASSWORD\n" | passwd $AMAN

	# create php7-fpm configuration 
	mkdir /home/${AMAN}/log
	create_log_dir php7
	create_log_dir php-fpm
	for i in php php71 php72 php73 php74
	do
		/usr/src/create-${i}-conf -d $AMAN -u $AMAN
	done
	chown -R $AMAN:$AMAN /home/${AMAN}/log

	# create FileManager
	mkdir -p /home/$AMAN/.FileManager
	unzip -qq -d /home/$AMAN/.FileManager /usr/src/cPanel/FileManager_source/Webmaster_Filerun_sample.zip
	cat <<EOT > /home/$AMAN/.FileManager/system/data/autoconfig.php
<?php
\$config['db'] = array (
	'type' => 'null',
	'server' => 'localhost',
	'database' => 'Filerun_${AMAN}_db',
	'username' => 'Filerun_${AMAN}_user',
	'password' => '$FileP',
);
EOT
	echo "$FileP" | cat > /home/$AMAN/.FileManager/system/data/lifeconfig
	chmod 400 /home/$AMAN/.FileManager/system/data/lifeconfig
	chown -R $AMAN:$AMAN /home/$AMAN/.FileManager/
	sed -i "/kusanagilifesafe_user/a\    'deny Filerun_${AMAN}_user from all'," /usr/share/mysqlmanager/config.inc.php
	mysql -p$GetP -e "drop database if exists Filerun_"$AMAN"_db"
	mysql -p$GetP -e "create database Filerun_"$AMAN"_db"
	mysql -p$GetP -e "create user 'Filerun_"$AMAN"_user'@'%' identified with mysql_native_password;"
	mysql -p$GetP -e "set old_passwords = 0;"
	mysql -p$GetP -e "set password for 'Filerun_"$AMAN"_user'@'%' = password('$FileP')"
	mysql -p$GetP -e "grant all privileges on Filerun_"$AMAN"_db.* to 'Filerun_"$AMAN"_user'@'%'"
	mysql -p$GetP -e "flush privileges"
	mysql -p$GetP Filerun_"$AMAN"_db < /usr/src/cPanel/FileManager_source/Filerun_webmaster_db.sql
    mysql -p$GetP Filerun_"$AMAN"_db -e "UPDATE df_users SET username = '"$AMAN"'"
	#echo "$AMAN" $?
	echo -e "/usr/src/clean_Filerundb -u $AMAN" >> /usr/src/clean-Filerun
	# set disk quota
	xfs_quota -x -c 'limit bsoft='$bsoft'm bhard='$bhard'm '$AMAN'' /home
	xfs_quota -x -c 'limit -g bsoft='$bsoft'm bhard='$bhard'm '$AMAN'' /home
	# set inode quota
	xfs_quota -x -c 'limit isoft='$isoft' ihard='$ihard' '$AMAN'' /home
	xfs_quota -x -c 'limit -g isoft='$isoft' ihard='$ihard' '$AMAN'' /home
	# apply to lve limit
	uid=`id -u $AMAN`
	echo $uid ${pkg[$PLAN]} >> /var/superpanel/user_package
	echo $uid","${pkg[$PLAN]}"," >> /var/superpanel/users
	lvectl apply $uid
	# update dbuser belong to this user to dbuser-map file
	/usr/src/dbuser-map-update $AMAN
	# cagefs custom
	mkdir -p /etc/cagefs/custom.etc/$AMAN
	cp -f /usr/src/cPanel/hosts /etc/cagefs/custom.etc/$AMAN/hosts
	chown -R $AMAN:$AMAN /etc/cagefs/custom.etc/$AMAN/
	cagefsctl --update-etc $AMAN
	echo " /usr/local/maldetect/maldet --scan-all /home/$AMAN" >> /usr/src/maldet_user
	exit 0
fi
