#!/bin/bash

GetP=`cat /usr/src/.lifesafty_cPanel | head -c 24`
FileP=`openssl rand -base64 32`
function usage() {
   echo " Usage $0 -u user"
   exit 1
}
while getopts u: OPT
	do
		case $OPT in
		 "u" ) AMAN="$OPTARG" ;;
		 "*" ) usage ;;
		esac
	done
if [ -z ${AMAN} ]; then
	usage
fi
	# create FileManager
	if [ -d "/home/$AMAN/.FileManager" ]; then
		rm -rf /home/$AMAN/.FileManager
	fi
	mkdir -p /home/$AMAN/.FileManager
	unzip -qq -d /home/$AMAN/.FileManager /usr/src/cPanel/FileManager_source/Webmaster_Filerun_sample.zip
	cat <<EOT > /home/$AMAN/.FileManager/system/data/autoconfig.php
<?php
\$config['db'] = array (
	'type' => 'null',
	'server' => 'localhost',
	'database' => 'Filerun_${AMAN}_db',
	'username' => 'Filerun_${AMAN}_user',
	'password' => '$FileP',
);
EOT
	echo "$FileP" | cat > /home/$AMAN/.FileManager/system/data/lifeconfig
	chown -R $AMAN:$AMAN /home/$AMAN/.FileManager/
	chmod 400 /home/$AMAN/.FileManager/system/data/lifeconfig
	mysql -p$GetP -e "drop database if exists Filerun_"$AMAN"_db"
	mysql -p$GetP -e "create database Filerun_"$AMAN"_db"
	mysql -p$GetP -e "drop user Filerun_"$AMAN"_user"
	mysql -p$GetP -e "create user 'Filerun_"$AMAN"_user'@'%' identified with mysql_native_password;"
	mysql -p$GetP -e "set old_passwords = 0;"
	mysql -p$GetP -e "set password for 'Filerun_"$AMAN"_user'@'%' = password('$FileP')"
	mysql -p$GetP -e "grant all privileges on Filerun_"$AMAN"_db.* to 'Filerun_"$AMAN"_user'@'%'"
	mysql -p$GetP -e "flush privileges"
	mysql -p$GetP Filerun_"$AMAN"_db < /usr/src/cPanel/FileManager_source/Filerun_webmaster_db.sql
    mysql -p$GetP Filerun_"$AMAN"_db -e "update df_users set username = '"$AMAN"'"
	chown -R $AMAN:$AMAN /home/$AMAN/
	exit 0

