#!/bin/bash
function usage() {
	echo " Restart all php & hhvm "
	echo " Usage $0 -u user "
	exit 1
}
while getopts u: OPT
	do
		case $OPT in
		  "u" ) USERNAME="$OPTARG" ;;
		  "*" ) usage ;;
		esac
	done
if [ -z ${USERNAME} ]; then
	usage
fi
kusanagi restart_php $USERNAME
