#!/bin/bash
function usage() {
	echo " Restart all php & hhvm "
	echo " Usage $0 -u user "
	exit 1
}
while getopts u: OPT
	do
		case $OPT in
		  "u" ) USERNAME="$OPTARG" ;;
		  "*" ) usage ;;
		esac
	done
if [ -z ${USERNAME} ]; then
	usage
fi
#systemctl restart php7-fpm.$USERNAME
#for i in php 
#do
#	if [ 0 -eq $(ls /etc/$i-fpm.d/conf.d/$USERNAME.conf > /dev/null; echo $?) ] ; then
#				systemctl restart $i-fpm.$USERNAME; echo $?
#														fi				
#	done
#exit 0
kusanagi restart_php $USERNAME
