#!/bin/bash

func_usage()
{
  echo " Usage: $0 -u dst_user -d dst_domain -t time -s src_server -v src_user -p src_domain"
  exit 1
}
while getopts u:d:t:s:v:p: OPT
	do
		case $OPT in
		"u" ) _USER="$OPTARG" ;;
		"d" ) _DOMA="$OPTARG" ;;
		"t" ) _TIME="$OPTARG" ;;
		"s" ) srv_hostname="$OPTARG" ;;
		"v" ) src_user="$OPTARG" ;;
		"p" ) src_dom="$OPTARG" ;;
		* ) func_usage ;;
		esac
	done
if [ -z ${_USER} ] || [ -z ${_DOMA} ] || [ -z ${_TIME} ] || [ -z ${srv_hostname} ] || [ -z ${src_user} ] || [ -z ${src_dom} ] ; then
    func_usage
fi

w3-date ()
{
declare -A arrayDate
arrayDate=( ["Jan"]=01 ["Feb"]=02 ["Mar"]=03 ["Apr"]=04 ["May"]=05 ["Jun"]=06 ["Jul"]=07 ["Aug"]=08 ["Sep"]=09 ["Oct"]=10 ["Nov"]=11 ["Dec"]=12 )
time_in_day=`echo $1 |cut -d '-' -f2`
mon=`echo $1 |cut -d '-' -f1| cut -d '/' -f2`
mon=${arrayDate[$mon]}
year=`echo $1 |cut -d '-' -f1| cut -d '/' -f1`
day=`echo $1 |cut -d '-' -f1| cut -d '/' -f3`
[ $day -lt 10 ] && day="0"$day
echo $year"-"$mon"-"$day"T"$time_in_day"+07:00"
}
#srv_hostname=`hostname`
w3date=$(w3-date ${_TIME})
passwd=`cat /usr/src/.lifesafty_cPanel | head -c 24`
## restore source code
src_dir="/home/${_USER}/${_DOMA}/"
dest_url="file:///backup/$srv_hostname/${src_user}/${src_dom}"
log_archive="/var/log/${_DOMA}/rest.log"
today=`date +%Y-%m-%d-%H:%M:%S`
echo $today >> $log_archive
duplicity --time=${w3date} --no-encryption $dest_url $src_dir --force >> $log_archive
ret=$?
if [ $ret -eq 0 ]; then
	## restore db
	db=`grep "/${_DOMA}\"" /etc/kusanagi.d/profile.conf -A 1 | grep DBNAME | cut -d '"' -f2`
	sql_dir="/home/${_USER}/${_DOMA}/sqlbackup"
	if [ -f $sql_dir/$db".sql.gz" ]; then
		echo "drop old $db database"
		mysql  -p$passwd -e "drop database if exists $db"
		echo $?
		echo "create new $db database and restore from backup"
		mysql  -p$passwd -e "create database $db"
		gunzip < $sql_dir/$db".sql.gz" | mysql  -p$passwd $db 
		echo $?
	else
		echo $db".sql.gz does NOT exist"
		echo 1
	fi
else
	echo "Restoration failed ! Contact your provider for help!"
	echo 1
fi
