#!/bin/bash
function usage() {
	echo " Suspend user"
	echo " Usage $0 -u user "
	exit 1
}

while getopts u: OPT
	do
		case $OPT in
		  "u" ) USERNAME="$OPTARG" ;;
		  "*" ) usage ;;
		esac
	done
if [ -z ${USERNAME} ]; then
	usage
fi

[ ! -f "/root/.tmp/suspend.log" ] && touch /root/.tmp/suspend.log
sed -i '/'$USERNAME'/d' /root/.tmp/suspend.log
for i in php php7 php71 php72 php73 php74
do
	if [ 0 -eq $(systemctl is-active $i-fpm.$USERNAME > /dev/null 2>&1; echo $?) ] ; then
		echo "$i.$USERNAME" >> /root/.tmp/suspend.log
		systemctl stop $i-fpm.$USERNAME
		systemctl disable $i-fpm.$USERNAME
		#mv -f /etc/$i-fpm.d/www.${USERNAME}.conf /etc/$i-fpm.d/www.${USERNAME}.conf.suspend
		rm -f /etc/$i-fpm.d/www.${USERNAME}.conf
	fi
done

GetP=`cat /usr/src/.lifesafty_cPanel | head -c 24`
mysql -p$GetP -h localhost kusanagi -e "UPDATE account SET status = 0 WHERE login_id = '"$USERNAME"'"
echo $?
