#!/bin/bash
function usage() {
	echo " Unsuspend user"
	echo " Usage $0 -u user "
	exit 1
}
while getopts u: OPT
	do
		case $OPT in
		  "u" ) USERNAME="$OPTARG" ;;
		  "*" ) usage ;;
		esac
	done
if [ -z ${USERNAME} ]; then
	usage
fi

GetP=`cat /usr/src/.lifesafty_cPanel | head -c 24`

status_check=`/usr/src/select_disable_account | grep ${USERNAME} > /dev/null 2>&1; echo $?`
if [ $status_check -gt 0 ]; then
	mysql -p$GetP kusanagi -e "UPDATE account SET status = 1 WHERE login_id = '"$USERNAME"'"; echo $?
	exit 0
fi

[ ! -f "/root/.tmp/unsuspend.log" ] && touch /root/.tmp/unsuspend.log
PHP=`cat /root/.tmp/suspend.log | grep $USERNAME | cut -d "." -f1`
for i in $PHP; do
	echo "$i.$USERNAME" >> /root/.tmp/unsuspend.log
	/usr/src/create-$i-conf -d ${USERNAME} -u ${USERNAME}
	systemctl start $i-fpm.$USERNAME
	systemctl enable $i-fpm.$USERNAME
done

mysql -p$GetP kusanagi -e "UPDATE account SET status = 1 WHERE login_id = '"$USERNAME"'"; echo $?
