#!/bin/bash
dbr=`grep password /root/.my.cnf | cut -d '"' -f 2`
old=`grep password /etc/container/mysql-governor.xml | cut -d '"' -f 6`
sed -i 's/'$old'/'$dbr'/' /etc/container/mysql-governor.xml
systemctl restart db_governor
