#!/bin/bash
main() {
base_dir="/opt/maintenance/backup_tools"
/usr/src/get_token
cat error_backup.txt |\
while read line; do
	user_=`echo $line |cut -d ':' -f1`
	prov_=`echo $line |cut -d ':' -f2`
	exist=`echo $line |grep 'does not exist' > /dev/null 2>&1;echo $?`
	if [ 0 -eq $exist ]; then
		echo "$user_---$prov_---doesnt exist"
		${base_dir}/delete-death-backup-provision-single $user_ $prov_
	else
		echo "$user_---$prov_"
		${base_dir}/fix_error_backup_single  -u $user_ -p $prov_
	fi
done
}

main
