#!/bin/bash

check_ssh_con ()
{
if [ 255 -eq $(ssh -p22999 -q $1 exit;echo $?) ]; then
	echo " Cannot SSH to server $1 "
	exit 1
fi
}

check_cert_existed ()
{
    if [ -f "/etc/pki/tls/certs/${1}.crt" ]; then echo 1; else echo 0; fi
}
check_lets_existed ()
{
    if [ -d "/etc/letsencrypt/live/${1}" ]; then echo 1; else echo 0; fi
}
proxy_prepare()
{
remote_ip=`ssh -p 22999 $2 'hostname -I' | awk '{print $1}'`
local_ip=`hostname -I | awk '{print $1}'`
#echo $remote_ip"---"$local_ip
sed 's/'$local_ip'/'$remote_ip'/'g /etc/proxy/${1}_http.conf > /opt/scripts2/${1}_http.conf
sed 's/'$local_ip'/'$remote_ip'/'g /etc/proxy/${1}_ssl.conf > /opt/scripts2/${1}_ssl.conf
}
rsync_procedure()
{
check_ssh_con $2
if [ 1 -eq $(check_cert_existed $1) ]; then
	rsync -avzh -e 'ssh -p 22999' /etc/pki/tls/certs/${1}* ${2}:/etc/pki/tls/certs/ 2>&1 > /dev/null
	rsync -avzh -e 'ssh -p 22999' /etc/pki/tls/private/${1}* ${2}:/etc/pki/tls/private/ 2>&1 > /dev/null
fi

if [ 1 -eq $(check_lets_existed $1) ]; then
	rsync -avzh -e 'ssh -p 22999' /etc/letsencrypt/live/${1} ${2}:/etc/letsencrypt/live/ 2>&1 > /dev/null
	rsync -avzh -e 'ssh -p 22999' /etc/letsencrypt/archive/${1} ${2}:/etc/letsencrypt/archive/ 2>&1 > /dev/null
	if [ 0 -eq $(ls /etc/letsencrypt/archive/${1}-* > /dev/null 2>&1;echo $?) ]; then
		rsync -avzh -e 'ssh -p 22999' /etc/letsencrypt/live/${1}-* ${2}:/etc/letsencrypt/live/ 2>&1 > /dev/null
		rsync -avzh -e 'ssh -p 22999' /etc/letsencrypt/archive/${1}-* ${2}:/etc/letsencrypt/archive/ 2>&1 > /dev/null
	fi
fi
proxy_prepare $1 $2
rsync -avzh -e 'ssh -p 22999' /opt/scripts2/${1}_* ${2}:/etc/proxy/ 2>&1 > /dev/null
rsync -avzh -e 'ssh -p 22999' /etc/nginx/conf.d/${1}_* ${2}:/etc/nginx/conf.d/ 2>&1 > /dev/null

ret=$?
rm -f /opt/scripts2/${1}_*
if [ 1 -eq $ret ]; then
	echo " Rsync error"
	exit 1
fi
}
